# powerlevel9k theme
# AtomicCoding's Configuration
POWERLEVEL9K_MODE='awesome-fontconfig'
VIRTUAL_ENV_DISABLE_PROMPT=1
POWERLEVEL9K_PYTHON_ICON='\U1F40D '

POWERLEVEL9K_PROMPT_ON_NEWLINE=true
POWERLEVEL9K_PROMPT_ADD_NEWLINE=true
POWERLEVEL9K_RPROMPT_ON_NEWLINE=true
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(context os_icon virtualenv root_indicator dir_writable dir vcs )
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=()
